### ISSUE TITLE
Make the readme show decoded metadata.

### ISSUE THREAD

**Issue by i30817** [chyyran/chd-rs-py#2]
Quite simple, instead of printing the data directly do:
```
for m in metadata:
    print(i.tag().to_bytes(4, byteorder='big'), bytes(i.data()).decode())
```

so that people can know how to search for the str values they expect in the data/tags.

I wouldn't mind a example of how to extract tracks either. I can't get my head around how to use the Frames and maybe Pad in conjunction with the hunks to get the uncompressed bytes of each track (and i don't know what, if anything the other values do).

I can understand easily that for the track metadata i can extract only the tags with b'CHGD' (gdi) and b'CHT2' (and maybe b'CHCD' for 'legacy track cdrom metadata'), then i have to decompress (somehow, in the hunks don't already do that), but the rest of the owl...

**Comment by i30817** [comment]
Oh, we can't decompress yet right? According to the bug on chd-rs anyway.

**Comment by chyyran** [comment]
compression (i.e. write) is not implemented. decompression works fine, the hunk data returned is the decompressed hunk

[documentation](https://docs.rs/chd/latest/chd/struct.ChdHunk.html#method.read_hunk_in)

**Comment by i30817** [comment]
It's a bit annoying that with the header only there is no way to tell it's a cdrom or a harddrive chd.

That is, you can figure out that you need to get a parent with 'has_parent', but you can't figure out it's a cdrom without building it completely.

Should the header have a extra method, something like 'tags()' that shows the tags without the tag data? Or assuming that metadata will never be that big, just the Metadata object array.

The whole idea of using a header function was not having a 'half built' Chd object for Chd requiring parents, so having to built it completely just to discard it when you find the chd that you're processing is a hard_drive is a bit of a letdown.

Oh well, i'm sure that it will be fine.

**Comment by chyyran** [comment]
The header only contains the [offset to the metadata entries](https://docs.rs/chd/latest/src/chd/header.rs.html#802) which have to be read separately anyways. The format is in a linked list where the current entry points to the next one until the last one points to offset 0.

"Building" a CHD is a relatively cheap operation. No hunks are actually read until you call `hunks`, only the header.

**Comment by chyyran** [comment]
@i30817 As of `chd-rs@0.2`, [`Chd::open`](https://docs.rs/chd/latest/chd/struct.Chd.html#method.open) will now late-fail on hunk read when opening a CHD file that has a parent, that doesn't have one. This better matches the behaviour in [chd.cpp](https://github.com/mamedev/mame/blob/master/src/lib/util/chd.cpp#L2438). You can now iterate on metadata without needing the parent CHD.

I've pushed this as `chd-rs-py@0.1.5` on pypi.

**Comment by i30817** [comment]
I've decided to start using that project you linked to and depends on chd-rs, imageparse, since the author kindly implemented the parent constructor and sha1 track functionality i wanted in [4f307e9a2e1b5b063240cf4a01f2437ccac4b37d](https://github.com/Manorhos/imageparse/commit/4f307e9a2e1b5b063240cf4a01f2437ccac4b37d) and [b95a70560d24fff17c1cdc01efb5cee91f070e20](https://github.com/Manorhos/imageparse/commit/b95a70560d24fff17c1cdc01efb5cee91f070e20).

Now i just need to follow the example of this project and create a maturin wheel for that project (hopefully with the maturin github action and not compiling myself on windows and macos, which i can't).
